"""Updated methods

Revision ID: 85b8b85aa4d7
Revises: cc1e045b5275
Create Date: 2024-02-22 00:38:57.320721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b8b85aa4d7'
down_revision = 'cc1e045b5275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
